In [39]:
#Task 1
import pandas as pd

#Read the CSV file inot a DataFrame called GRc_df
Grc_df = pd.read_csv('data/Grocery_dataset.csv')

#Check the number of rows and columns in the DataFrame
print(f"Number of rows and columns: {Grc_df.shape}")

#Show the first 10 rows of the DataFrame
print("First 10 rows of the DataFrame:")
print(Grc_df.head(10))

#Show the last 10 rows of the DataFrame
print("Last 10 rows of the DataFrame:")
print(Grc_df.tail(10))

Number of rows and columns: (5000, 12)
First 10 rows of the DataFrame:
  Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15        9.300          Low Fat         0.016047
1           DRC01        5.920          Regular         0.019278
2           FDN15       17.500          Low Fat         0.016760
3           FDX07       19.200          Regular         0.000000
4           NCD19        8.930          Low Fat         0.000000
5           FDP36       10.395          Regular         0.000000
6           FDO10       13.650          Regular         0.012741
7           FDP10          NaN          Low Fat         0.127470
8           FDH17       16.200          Regular         0.016687
9           FDU28       19.200          Regular         0.094450

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049
1            Soft Drinks   48.2692            OUT018
2                   Meat  141.6180            OUT049
3  Fruits and Vegetables  182.0950            OUT010
4              Household   53.8614            OUT013
5           Baking Goods   51.4008            OUT018
6            Snack Foods   57.6588            OUT013
7            Snack Foods  107.7622            OUT027
8           Frozen Foods   96.9726            OUT045
9           Frozen Foods  187.8214            OUT017

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1
1                       2009      Medium               Tier 3
2                       1999      Medium               Tier 1
3                       1998         NaN               Tier 3
4                       1987        High               Tier 3
5                       2009      Medium               Tier 3
6                       1987        High               Tier 3
7                       1985      Medium               Tier 3
8                       2002         NaN               Tier 2
9                       2007         NaN               Tier 2

         Outlet_Type  Item_Outlet_Sales
0  Supermarket Type1          3735.1380
1  Supermarket Type2           443.4228
2  Supermarket Type1          2097.2700
3      Grocery Store           732.3800
4  Supermarket Type1           994.7052
5  Supermarket Type2           556.6088
6  Supermarket Type1           343.5528
7  Supermarket Type3          4022.7636
8  Supermarket Type1          1076.5986
9  Supermarket Type1          4710.5350
Last 10 rows of the DataFrame:
     Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
4990           FDE46        18.60          Low Fat         0.015859
4991           NCQ53        17.60          Low Fat         0.018905
4992           NCN42        20.25          Low Fat         0.014281
4993           DRH11         5.98          Low Fat         0.075675
4994           NCI42        18.75          Low Fat         0.010382
4995           FDT07         5.82          Regular         0.077476
4996           DRL60         8.52          Low Fat         0.027059
4997           FDG20        15.50          Regular         0.126200
4998           FDF56        16.70          Regular         0.119462
4999           FDV33         9.60          Regular         0.027455

                  Item_Type  Item_MRP Outlet_Identifier  \
4990            Snack Foods  152.9366            OUT017
4991     Health and Hygiene  234.6590            OUT046
4992              Household  148.0418            OUT018
4993            Hard Drinks   53.3614            OUT049
4994              Household  207.8954            OUT049
4995  Fruits and Vegetables  255.3330            OUT045
4996            Soft Drinks  153.3682            OUT046
4997  Fruits and Vegetables  178.4028            OUT018
4998  Fruits and Vegetables  182.7976            OUT046
4999            Snack Foods  258.1304            OUT018

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
4990                       2007         NaN               Tier 2
4991                       1997       Small               Tier 1
4992                       2009      Medium               Tier 3
4993                       1999      Medium               Tier 1
4994                       1999      Medium               Tier 1
4995                       2002         NaN               Tier 2
4996                       1997       Small               Tier 1
4997                       2009      Medium               Tier 3
4998                       1997       Small               Tier 1
4999                       2009      Medium               Tier 3

            Outlet_Type  Item_Outlet_Sales
4990  Supermarket Type1           453.4098
4991  Supermarket Type1          8508.9240
4992  Supermarket Type2          1177.1344
4993  Supermarket Type1           331.5684
4994  Supermarket Type1          2292.3494
4995  Supermarket Type1          4870.3270
4996  Supermarket Type1           914.8092
4997  Supermarket Type2          1239.7196
4998  Supermarket Type1          1810.9760
4999  Supermarket Type2          2324.9736

In [38]:
# Task 2: Check for null values and handle them

# Check for null values and print in a readable format
null_counts = Grc_df.isna().sum()
print("Null values in each column before handling:")
print(null_counts[null_counts > 0])  # Display only columns with null values

# Handle null values by dropping them
Grc_df.dropna(inplace = True)

# Check for null values after handling them
Grc_df.isna().sum()

Null values in each column before handling:
Item_Weight     818
Outlet_Size    1439
dtype: int64

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64